build:
  image: centos
  commands:
    - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - yum install -y install git python-setuptools gcc sudo libffi-devel python-devel openssl-devel
    - yum install -y python-pip
    - pip install --upgrade pip
    - pip install ansible
    - pip install docker-py
    - pip install molecule
    - curl https://get.docker.com | sh
    - molecule test
